### ISSUE TITLE
添加图片浏览功能

### ISSUE THREAD

**Issue by iOkay** [j178/fanfou-cli#4]
希望添加图片浏览功能来查看一条消息中的图片。

**Comment by j178** [comment]
哈哈，终端里看图片有点困难啊/_\
好像有一些终端可以显示简单的图片，但是兼容性和跨平台比较麻烦。
默认的时间线只以 `[图]` 这样的方式表示图片，如果想看图片，则用 `p 序号` 这样的命令，使用第三方的图片浏览器打开图片，这样可以吗？
你有什么好方法吗？

**Comment by iOkay** [comment]
嗯，终端里看图片是不容易。我尝试了下使用simshow，可以将图片在IPython中显示，不过效果不是很好，很简陋，不支持gif。实现这个功能估计需要很大的工作量。

**Comment by iOkay** [comment]
iterm2中可以显示图片 可以使用imgcat脚本
