### ISSUE TITLE
浏览模式添加刷新功能

### ISSUE THREAD

**Issue by iOkay** [j178/fanfou-cli#5]
如题

**Comment by j178** [comment]
这样终端上的操作和现实都会变得好复杂…/_\
退出去，再重新`fan -v`一下不就是最新的吗😅

**Comment by iOkay** [comment]
这个操作可以和下一页的操作一样只是重置获取信息时的起始点，将max_id置为None。这样就不需要退出浏览模式再进入浏览模式来进行刷新了。

**Comment by j178** [comment]
嗯嗯，我看到你的commit了，我觉得这样非常巧妙…希望你能把commit PR给我，谢谢😁

**Comment by iOkay** [comment]
#6
