### ISSUE TITLE
关于饭否发图片的接口疑问

### ISSUE THREAD

**Issue by yolo2013** [j178/fanfou-cli#9]
我正在用nodejs写饭否的proxy服务器，但是在发送图片时，始终报缺少photo参数，我使用postman直接发送也有这个问题（oauth认证都已经通过了），给出postman的参数图片
![image](https://user-images.githubusercontent.com/5243482/27337525-3998740c-5605-11e7-8217-bb68cf4e8b51.png)

想请问下你有没有遇到这个问题，如果这个问题实在用nodejs解决不了，都想考虑学python来写这个服务了。

**Comment by j178** [comment]
其他API调用是否正常？

**Comment by yolo2013** [comment]
@j178 其它都是正常的，我起初认为主要原因是只有这个需要multipart/form-data提交。现在发现似乎还有另外的原因。

**Comment by j178** [comment]
的确是只有这个才需要 multipart/form-data，这是我在发图片时抓的包
http://imgur.com/EzmIQug
(GitHub上传图片一直失败…)
你可以抓包看一下是不是你的用的库multipart/form-data编码不正确。

**Comment by yolo2013** [comment]
好的，我这里抓了御饭发图片的包，我再尝试下别的方法，多谢你。

**Comment by LitoMore** [comment]
@yolo2013 饭否的 [/photos/upload](https://github.com/FanfouAPI/FanFouAPIDoc/wiki/photos.upload) 接口的格式参考 [RFC 1867](http://www.ietf.org/rfc/rfc1867.txt)

Node.js 有现成的 [fanfou-sdk](https://github.com/LitoMore/fanfou-sdk-node) 支持发送图片

具体的实现代码可以见 [fanfou-sdk/fanfou.js#L243](https://github.com/LitoMore/fanfou-sdk-node/blob/master/src/fanfou.js#L243)

**Comment by yolo2013** [comment]
@LitoMore 感谢，之前我自己已经解决了.
